# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 02fa89bacf96b7d7eb767a228b2a16109d6e99942a3f69c2ec6fa7e775380af5c1209b0f9acc36cc2824cf77dfc2387e267b48be6e473affc0a71e00a2530c6d

test:
  secret_key_base: 4778f73d776671dc05b7b9341adde807ebaf6864fad889f8edca9586af77e89b0a87b654ed44f8689f9a3b961ea3248d763c6e1e6a52feb116de48ccd3904e5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
